// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE9bXSwHpig8OQhlgR-kORDy1WVPoG8S4',
    appId: '1:446676176926:web:d61360acc1c0c860411e0f',
    messagingSenderId: '446676176926',
    projectId: 'ditonton-e1588',
    authDomain: 'ditonton-e1588.firebaseapp.com',
    storageBucket: 'ditonton-e1588.appspot.com',
    measurementId: 'G-7X54T4WXWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBl-BWqjXev6NAtCL8Hw00_p1kegyB_m8',
    appId: '1:446676176926:android:62d06339af1a7f9b411e0f',
    messagingSenderId: '446676176926',
    projectId: 'ditonton-e1588',
    storageBucket: 'ditonton-e1588.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGBxoB04W3j3vLOtz02BE8Vtwr0yoBqf0',
    appId: '1:446676176926:ios:e875205630c3c0f4411e0f',
    messagingSenderId: '446676176926',
    projectId: 'ditonton-e1588',
    storageBucket: 'ditonton-e1588.appspot.com',
    iosClientId: '446676176926-2vf5fj6rq0a91apnnbv93u89b3megabi.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton.ericthioko',
  );
}
